Preventing email leak in FIDO login and counting login attempts
team-pass/FIDO-login pull request #72
Opened 2022-03-09 19:23 UTC by jckong99

On #60:
- Only attempts to hide email leaks from FIDO login, not any registration routes.
- Currently unable to test because, when logging in with an unregistered email, Windows notices that there are no credentials associated with it and does not offer biometric options, leaving only a security key as a sign-in method.

On #71:
- Password success/failure counts have locally been tested to be accurate.
- As described in [Balaji's comment](https://github.com/team-pass/FIDO-login/issues/71#issuecomment-1063269129), there does not appear to be an easy way to count FIDO failures, since, for example, bad fingerprint readings are localized to the FIDO authenticator and our server receives nothing. The code still implements attempt counting as if it worked.

2022-03-09 20:03 UTC, jckong99 commented
So, I forgot to create a new branch and accidentally made changes for #50 here. I feel like instructions were already kind of covered by the earlier addition of the "Daily Remaining Tasks" list on the user profile page, so I just extended that by including list items for registering any missing authentication options and adding a general statement to explain their purpose.

2022-03-11 18:28 UTC, zbreit requested changes
I just made a few suggestions. I also created a DB migration for your new table, which I'll push in a sec. Please let me know if you have any questions!

2022-03-11 18:28 UTC, zbreit commented on web/fido_app/models.py
> +    email = db.Column(db.String(80), nullable=False)
Do we want to distinguish between failed FIDO vs password logins?

2022-03-11 18:28 UTC, zbreit commented on web/fido_app/models.py
> +    email = db.Column(db.String(80), nullable=False)
I know we can't accurately count all FIDO failures, but our model might want to account for this, at least. One option is just to add a `password_successes`, `password_failures`, `fido_successes`, and `fido_failures` fields

2022-03-11 21:15 UTC, jckong99 commented on web/fido_app/webauthn_routes.py
> +        authentication_options = generate_authentication_options(
Added in [2e344d6](https://github.com/team-pass/FIDO-login/pull/72/commits/2e344d619a22ae193455b72059abfa8544599a11)

2022-03-11 21:16 UTC, jckong99 commented on web/fido_app/routes.py
>          flash('You have not configured a password for your account', 'error')
Changed in [37b53ba](https://github.com/team-pass/FIDO-login/pull/72/commits/37b53ba267c298c30a48ddead5c3b8fb5c5d0bf8)

2022-03-13 01:47 UTC, zbreit approved these changes
LGTM

2022-03-13 01:47 UTC, merged