Added authentication method to each interaction
team-pass/FIDO-login pull request #75
Opened 2022-03-10 21:15 UTC by bkodali12

Addresses #67 

I have implemented a login_method field for the Interaction table such that it provides the authentication method a user is using to login.

2022-03-11 16:03 UTC, jckong99 requested changes

2022-03-11 16:03 UTC, jckong99 commented on web/fido_app/models.py
> +    login_method = db.Column(db.Integer, default=0) # 0 is not logging in, 1 is webauthn, and 2 is password
I know that it would be functionally the same, but is there any reason that a field like this isn't an Enum? It would be nice for interpretability.

2022-03-12 17:42 UTC, jckong99 approved these changes

2022-03-13 01:11 UTC, zbreit approved these changes
Looks good to me! 

I'm going to push a change where I add a database migration for the new field that you added. You can generate a DB migration using the command `flask db migrate -m "migration message"`. Then, you upgrade your database to the latest revision using `flask db upgrade`.

2022-03-13 01:19 UTC, merged